# -*- coding: utf-8 -*-
"""HW_9_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PEbOwCiPnoGsNFJrhu2o0XPkI94vAuJ0
"""

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')

"""Задача 40: Работать с файлом california_housing_train.csv, который находится в папке sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population)."""

df

print(df['median_house_value'].sum())

print(df['median_house_value'].mean())

df[df['population'] < 500]

print(df[df['population'] < 500]['median_house_value'].sum())

print(df[df['population'] < 500]['median_house_value'].mean())

"""Задача 42: Узнать какая максимальная households в зоне минимального значения population."""

#df[df['population'] < 20]

# print(df[df['population'] == 3]['households'].max())

df1 = df.loc[df.population < df.population.quantile(.15)]
print(df1)
print(df.population.quantile(.15))
print(df1.households.max())